---
deployment:
  tasks:
    - export APPPATH=/home2/wesl4494/padariacasadopao.com
    - export PUBLICPATH=/home2/wesl4494/public_html

    - /bin/rsync -av --exclude='.git' --exclude='.env' --exclude='vendor' --exclude='storage' --exclude='node_modules' ./ $APPPATH/

    - /bin/rsync -av public/ $PUBLICPATH/

    - /bin/cp $APPPATH/public/index.php $PUBLICPATH/index.php