@extends('default.layout', ['title' => 'Admin Pro V3'])

@section('content')
<div class="page-content"><div class="card"><div class="card-body">
<div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">Painel Admin Pro V3</h4><div><a href="/__admin/monitor" class="btn btn-secondary">Monitor</a> <a href="/__admin/audit" class="btn btn-info">Auditoria</a> <a href="/__admin/backups" class="btn btn-dark">Backups</a> <a href="/__admin/backup-now" class="btn btn-success">Criar Backup</a></div></div>
<div class="row"><div class="col-md-3 mb-3"><div class="card bg-primary text-white"><div class="card-body"><div>Vendas Hoje</div><h3 class="mb-0">{{ $vendasHoje }}</h3></div></div></div><div class="col-md-3 mb-3"><div class="card bg-success text-white"><div class="card-body"><div>Faturamento do Mês</div><h3 class="mb-0">R$ {{ number_format((float)$faturamentoMes, 2, ',', '.') }}</h3></div></div></div><div class="col-md-3 mb-3"><div class="card bg-warning text-white"><div class="card-body"><div>Contas Pendentes</div><h3 class="mb-0">{{ $contasPendentes }}</h3></div></div></div><div class="col-md-3 mb-3"><div class="card bg-danger text-white"><div class="card-body"><div>Caixas Abertos</div><h3 class="mb-0">{{ $caixasAbertos }}</h3></div></div></div></div>
<div class="row"><div class="col-md-8 mb-3"><div class="card"><div class="card-header"><strong>Gráfico de Vendas</strong></div><div class="card-body"><canvas id="salesChart" height="100"></canvas></div></div></div><div class="col-md-4 mb-3"><div class="card"><div class="card-header"><strong>Estoque Baixo</strong></div><div class="card-body">@if(count($estoqueBaixo) > 0)<ul class="mb-3">@foreach($estoqueBaixo as $p)<li>{{ $p->nome ?? '-' }} - <strong style="color:red">{{ $p->estoque }}</strong></li>@endforeach</ul><a href="/__admin/low-stock" class="btn btn-warning btn-sm">Ver todos</a>@else<div class="alert alert-success mb-0">Nenhum alerta de estoque.</div>@endif</div></div></div></div>
<div class="row"><div class="col-md-6 mb-3"><div class="card"><div class="card-header"><strong>Top Produtos</strong></div><div class="card-body"><ul class="mb-0">@forelse($topProdutos as $p)<li>{{ $p['nome'] }} - {{ $p['total'] }}</li>@empty<li>Sem dados</li>@endforelse</ul></div></div></div><div class="col-md-6 mb-3"><div class="card"><div class="card-header"><strong>Top Clientes</strong></div><div class="card-body"><p><strong>Usuários:</strong> {{ $usuariosOnline }}</p><ul class="mb-0">@forelse($topClientes as $c)<li>{{ $c['nome'] }} - {{ $c['total'] }}</li>@empty<li>Sem dados</li>@endforelse</ul></div></div></div></div>
</div></div></div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>fetch('/__admin/sales-chart').then(r=>r.json()).then(data=>{const labels=data.map(i=>i.dia);const values=data.map(i=>i.total);const ctx=document.getElementById('salesChart').getContext('2d');new Chart(ctx,{type:'line',data:{labels:labels,datasets:[{label:'Vendas',data:values,borderWidth:2,tension:0.2,fill:false}]},options:{responsive:true,plugins:{legend:{display:true}}}});});</script>
@endsection
